baseURL = "https://cloudbyvince.netlify.app/"
languageCode = "en-us"
title = "Vince | IT-Blog"
theme = "PaperMod"

[params]
    env = "production"
    title = "IT Blog"
    description = "Personal learnings about the cloud, coding and IT-infrastructure."
    author = "Vincent Wittlin"
    
    # ErmÃ¶glicht das Umschalten zwischen Dark- und Light-Mode
    defaultTheme = "auto" 
    
    # Zeigt Lesezeit und Wortzahl an
    ShowReadingTime = true
    ShowShareButtons = true
    ShowCodeCopyButtons = true # Essential fÃ¼r IT-Blogs!

    [params.homeInfoParams]
        Title = "Hi! ðŸ‘‹ My name is Vince and I'm glad you found my blog!"
        Content = "This blog is where I document all my learnings about IT - Whether it's from work or my studies."

    [[params.socialIcons]]
        name = "github"
        url = "https://github.com/vincentwtln"
    [[params.socialIcons]]
        name = "linkedin"
        url = "https://www.linkedin.com/in/vincent-wittlin-727905265/"

[menu]
    [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
        weight = 10
    [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        weight = 20