baseURL = "https://deine-seite.netlify.app/"
languageCode = "en-us"
title = "Vinc | IT-Blog"
theme = "PaperMod"

[params]
    env = "production"
    title = "Test-Blog"
    description = "Gedanken zu Cloud, Code und IT-Infrastruktur"
    author = "Vincent Wittlin"
    
    # ErmÃ¶glicht das Umschalten zwischen Dark- und Light-Mode
    defaultTheme = "auto" 
    
    # Zeigt Lesezeit und Wortzahl an
    ShowReadingTime = true
    ShowShareButtons = true
    ShowCodeCopyButtons = true # Essential fÃ¼r IT-Blogs!

    [params.homeInfoParams]
        Title = "Hallo! Ich bin Vinc ðŸ‘‹"
        Content = "Willkommen auf meinem Blog. Hier dokumentiere ich meine Reise durch die IT-Welt."

    [[params.socialIcons]]
        name = "github"
        url = "https://github.com/vincentwtln"
    [[params.socialIcons]]
        name = "linkedin"
        url = "https://www.linkedin.com/in/vincent-wittlin-727905265/"

[menu]
    [[menu.main]]
        identifier = "posts"
        name = "BeitrÃ¤ge"
        url = "/posts/"
        weight = 10
    [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        weight = 20